### ISSUE TITLE
mission page, image and profile are set way too far left on a small screen

### ISSUE THREAD

**Issue by andrewxhill** [Vizzuality/NEEMO#3]

**Comment by javierarce** [comment]
Fixed.

**Comment by andrewxhill** [comment]
This one is still an issue. I just put you to the start of the track, so if you open (on a laptop sized window),
http://neemo.cartodb.com:8080/mission.html
You'll see that it starts way on the left of the page. If you then move forward one track and reload, it will look fine.

**Comment by javierarce** [comment]
Ok, I think I've fixed it. The margin of the slideshow changes depending on if we have an image to the left or not.
